name: DevOps Demo
on:
  push:
  workflow_dispatch:
jobs:
  information:
    runs-on: ubuntu-latest
    steps:
      - name: Show Repository
        env:
          REPO: ${{ github.repository }}
        run: |
          echo "Repository: $REPO"
      - name: Show Branch
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          echo "Branch: $BRANCH"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Second Job
        run: echo "This is another job."
