name: DevOps Demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  information:
    runs-on: ubuntu-latest

    steps:
      - name: Show Repository
        env:
          REPO: ${{ github.repository }}
        run: |
          echo "Repository: $REPO"

      - name: Show Branch
        env:
          BRANCH: ${{ github.ref_name }}
        run: |
          echo "Branch: $BRANCH"

      - name: Show Actor
        env:
          ACTOR: ${{ github.actor }}
        run: |
          echo "Actor: $ACTOR"

  second-job:
    needs: information
    runs-on: ubuntu-latest

    steps:
      - name: Success Message
        run: echo "Workflow successfully completed!"
       
   
